### ISSUE TITLE
SSH Command fails when pty input is set to "true"

### ISSUE THREAD

**Issue by dumagalex** [CloudSlang/cs-actions#125]
ACTUAL BEHAVIOR:  The wrapper flow ssh_flow fails. When pty: "false" and the other inputs are the same, the run is successful.
The builder log writes: "DESCRIPTION=Post Input binding for operation/flow"
EXPECTED BEHAVIOR: ssh_flow runs successfully

HOW-TO-REPRODUCE: 
Run ssh_flow.sl with cslang-builder (9.57) by setting the following inputs in a .inputs.yaml test:
inputs:
  - host: LINUX_HOST
  - port: "22"
  - username: root
  - password: *
  - command: echo testing
  - pty: "true"

ENVIRONMENT: (Hardware, OS, OS Version, Browser, etc) 
Linux
 
NOTE The same issue was fixed for Studio content as #29414

**Comment by george-giloan** [comment]
A solution for this issue would be to write 'exit' at the end of the script when executed with pty set on true. Example:
>echo testing
>exit

When pty is set to true the channel used will not close automatically, so the operation times out because it waits for the channel to close. Appending 'exit' to your script will close the channel.

**Comment by tethryus** [comment]
Closed in cloud-slang-content PR: https://github.com/CloudSlang/cloud-slang-content/pull/757
@mihaitusa Since this issue was fixed in the operation, can we close it? WDYT?
